"""
This type stub file was generated by pyright.
"""

from kafka.future import Future

class FutureProduceResult(Future):
    def __init__(self, topic_partition) -> None: ...
    def success(self, value):  # -> Self:
        ...
    def failure(self, error):  # -> Self:
        ...
    def wait(self, timeout=...):  # -> bool:
        ...

class FutureRecordMetadata(Future):
    def __init__(
        self,
        produce_future,
        relative_offset,
        timestamp_ms,
        checksum,
        serialized_key_size,
        serialized_value_size,
        serialized_header_size,
    ) -> None: ...
    def get(self, timeout=...):  # -> None:
        ...

RecordMetadata = ...
