"""
This type stub file was generated by pyright.
"""

import threading
from collections.abc import Callable
from typing import Any, Self

from redis._parsers.encoders import Encoder
from redis.commands import CoreCommands, RedisModuleCommands, SentinelCommands
from redis.connection import ConnectionPool
from redis.credentials import CredentialProvider
from redis.retry import Retry

SYM_EMPTY = ...
EMPTY_RESPONSE = ...
NEVER_DECODE = ...

class CaseInsensitiveDict(dict):
    """Case insensitive dict implementation. Assumes string keys only."""

    def __init__(self, data: dict[str, str]) -> None: ...
    def __contains__(self, k):  # -> bool:
        ...
    def __delitem__(self, k):  # -> None:
        ...
    def __getitem__(self, k): ...
    def get(self, k, default=...): ...
    def __setitem__(self, k, v):  # -> None:
        ...
    def update(self, data):  # -> None:
        ...

class AbstractRedis: ...

class Redis(RedisModuleCommands, CoreCommands, SentinelCommands):
    """
    Implementation of the Redis protocol.

    This abstract class provides a Python interface to all Redis commands
    and an implementation of the Redis protocol.

    Pipelines derive from this, implementing how
    the commands are sent and received to the Redis server. Based on
    configuration, an instance will either use a ConnectionPool, or
    Connection object to talk to redis.

    It is not safe to pass PubSub or Pipeline objects between threads.
    """

    @classmethod
    def from_url(cls, url: str, **kwargs) -> Redis:
        """
        Return a Redis client object configured from the given URL

        For example::

            redis://[[username]:[password]]@localhost:6379/0
            rediss://[[username]:[password]]@localhost:6379/0
            unix://[username@]/path/to/socket.sock?db=0[&password=password]

        Three URL schemes are supported:

        - `redis://` creates a TCP socket connection. See more at:
          <https://www.iana.org/assignments/uri-schemes/prov/redis>
        - `rediss://` creates a SSL wrapped TCP socket connection. See more at:
          <https://www.iana.org/assignments/uri-schemes/prov/rediss>
        - ``unix://``: creates a Unix Domain Socket connection.

        The username, password, hostname, path and all querystring values
        are passed through urllib.parse.unquote in order to replace any
        percent-encoded values with their corresponding characters.

        There are several ways to specify a database number. The first value
        found will be used:

            1. A ``db`` querystring option, e.g. redis://localhost?db=0
            2. If using the redis:// or rediss:// schemes, the path argument
               of the url, e.g. redis://localhost/0
            3. A ``db`` keyword argument to this function.

        If none of these options are specified, the default db=0 is used.

        All querystring options are cast to their appropriate Python types.
        Boolean arguments can be specified with string values "True"/"False"
        or "Yes"/"No". Values that cannot be properly cast cause a
        ``ValueError`` to be raised. Once parsed, the querystring arguments
        and keyword arguments are passed to the ``ConnectionPool``'s
        class initializer. In the case of conflicting arguments, querystring
        arguments always win.

        """

    @classmethod
    def from_pool(cls: type[Redis], connection_pool: ConnectionPool) -> Redis:
        """
        Return a Redis client from the given connection pool.
        The Redis client will take ownership of the connection pool and
        close it when the Redis client is closed.
        """

    def __init__(
        self,
        host: str = "localhost",
        port: int = 6379,
        db: int = 0,
        password: Any = None,
        socket_timeout: Any = None,
        socket_connect_timeout: Any = None,
        socket_keepalive: Any = None,
        socket_keepalive_options: Any = None,
        connection_pool: Any = None,
        unix_socket_path: Any = None,
        encoding: str = "utf-8",
        encoding_errors: str = "strict",
        charset: Any = None,
        errors: Any = None,
        decode_responses: Any = False,
        retry_on_timeout: Any = False,
        retry_on_error: Any = None,
        ssl: Any = False,
        ssl_keyfile: Any = None,
        ssl_certfile: Any = None,
        ssl_cert_reqs: str = "required",
        ssl_ca_certs: Any = None,
        ssl_ca_path: Any = None,
        ssl_ca_data: Any = None,
        ssl_check_hostname: Any = False,
        ssl_password: Any = None,
        ssl_validate_ocsp: Any = False,
        ssl_validate_ocsp_stapled: Any = False,
        ssl_ocsp_context: Any = None,
        ssl_ocsp_expected_cert: Any = None,
        ssl_min_version: Any = None,
        ssl_ciphers: Any = None,
        max_connections: Any = None,
        single_connection_client: Any = False,
        health_check_interval: int = 0,
        client_name: Any = None,
        lib_name: str = "redis-py",
        lib_version: Any = ...,
        username: Any = None,
        retry: Any = None,
        redis_connect_func: Any = None,
        credential_provider: CredentialProvider | None = None,
        protocol: int | None = 2,
    ) -> None:
        """
        Initialize a new Redis client.
        To specify a retry policy for specific errors, first set
        `retry_on_error` to a list of the error/s to retry on, then set
        `retry` to a valid `Retry` object.
        To retry on TimeoutError, `retry_on_timeout` can also be set to `True`.

        Args:
        single_connection_client:
            if `True`, connection pool is not used. In that case `Redis`
            instance use is not thread safe.

        """

    def get_encoder(self) -> Encoder:
        """Get the connection pool's encoder"""

    def get_connection_kwargs(self) -> dict[Any, Any]:
        """Get the connection's key-word arguments"""

    def get_retry(self) -> Retry | None: ...
    def set_retry(self, retry: Retry) -> None: ...
    def set_response_callback(self, command: str, callback: Callable[..., Any]) -> None:
        """Set a custom Response Callback"""

    def load_external_module(self, funcname: Any, func: Callable[..., Any]) -> None:
        """
        This function can be used to add externally defined redis modules,
        and their namespaces to the redis client.

        funcname - A string containing the name of the function to create
        func - The function, being added to this class.

        ex: Assume that one has a custom redis module named foomod that
        creates command named 'foo.dothing' and 'foo.anotherthing' in redis.
        To load function functions into this namespace:

        from redis import Redis
        from foomodule import F
        r = Redis()
        r.load_external_module("foo", F)
        r.foo().dothing('your', 'arguments')

        For a concrete example see the reimport of the redisjson module in
        tests/test_connection.py::test_loading_external_modules
        """

    def pipeline(self, transaction: Any = ..., shard_hint: Any = ...) -> Pipeline:
        """
        Return a new pipeline object that can queue multiple commands for
        later execution. ``transaction`` indicates whether all commands
        should be executed atomically. Apart from making a group of operations
        atomic, pipelines are useful for reducing the back-and-forth overhead
        between the client and server.
        """

    def transaction(self, func: Callable[[Pipeline], None], *watches: Any, **kwargs: Any) -> None:
        """
        Convenience method for executing the callable `func` as a transaction
        while watching all keys specified in `watches`. The 'func' callable
        should expect a single argument which is a Pipeline object.
        """

    def lock(
        self,
        name: str,
        timeout: float | None = ...,
        sleep: float = ...,
        blocking: bool = ...,
        blocking_timeout: float | None = ...,
        lock_class: None | Any = ...,
        thread_local: bool = ...,
    ) -> Any:
        """
        Return a new Lock object using key ``name`` that mimics
        the behavior of threading.Lock.

        If specified, ``timeout`` indicates a maximum life for the lock.
        By default, it will remain locked until release() is called.

        ``sleep`` indicates the amount of time to sleep per loop iteration
        when the lock is in blocking mode and another client is currently
        holding the lock.

        ``blocking`` indicates whether calling ``acquire`` should block until
        the lock has been acquired or to fail immediately, causing ``acquire``
        to return False and the lock not being acquired. Defaults to True.
        Note this value can be overridden by passing a ``blocking``
        argument to ``acquire``.

        ``blocking_timeout`` indicates the maximum amount of time in seconds to
        spend trying to acquire the lock. A value of ``None`` indicates
        continue trying forever. ``blocking_timeout`` can be specified as a
        float or integer, both representing the number of seconds to wait.

        ``lock_class`` forces the specified lock implementation. Note that as
        of redis-py 3.0, the only lock class we implement is ``Lock`` (which is
        a Lua-based lock). So, it's unlikely you'll need this parameter, unless
        you have created your own custom lock class.

        ``thread_local`` indicates whether the lock token is placed in
        thread-local storage. By default, the token is placed in thread local
        storage so that a thread only sees its token, not a token set by
        another thread. Consider the following timeline:

            time: 0, thread-1 acquires `my-lock`, with a timeout of 5 seconds.
                     thread-1 sets the token to "abc"
            time: 1, thread-2 blocks trying to acquire `my-lock` using the
                     Lock instance.
            time: 5, thread-1 has not yet completed. redis expires the lock
                     key.
            time: 5, thread-2 acquired `my-lock` now that it's available.
                     thread-2 sets the token to "xyz"
            time: 6, thread-1 finishes its work and calls release(). if the
                     token is *not* stored in thread local storage, then
                     thread-1 would see the token value as "xyz" and would be
                     able to successfully release the thread-2's lock.

        In some use cases it's necessary to disable thread local storage. For
        example, if you have code where one thread acquires a lock and passes
        that lock instance to a worker thread to release later. If thread
        local storage isn't disabled in this case, the worker thread won't see
        the token set by the thread that acquired the lock. Our assumption
        is that these cases aren't common and as such default to using
        thread local storage.
        """

    def pubsub(self, **kwargs: Any) -> PubSub:
        """
        Return a Publish/Subscribe object. With this object, you can
        subscribe to channels and listen for messages that get published to
        them.
        """

    def monitor(self) -> Monitor: ...
    def client(self) -> Self: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    def __del__(self) -> None: ...
    def close(self) -> None: ...
    def execute_command(self, *args: Any, **options: Any) -> Any:
        """Execute a command and return a parsed response"""

    def parse_response(self, connection, command_name, **options):
        """Parses a response from the Redis server"""

    def smembers(self, name: str) -> list[bytes]:
        """
        Return all members of the set ``name``

        For more information see https://redis.io/commands/smembers
        """

StrictRedis = Redis

class Monitor:
    """
    Monitor is useful for handling the MONITOR command to the redis server.
    next_command() method returns one command from monitor
    listen() method yields commands from monitor.
    """

    monitor_re = ...
    command_re = ...
    def __init__(self, connection_pool) -> None: ...
    def __enter__(self):  # -> Self:
        ...
    def __exit__(self, *args):  # -> None:
        ...
    def next_command(self):  # -> dict[str, float | int | str | Any]:
        """Parse the response from a monitor command"""

    def listen(self):  # -> Generator[dict[str, float | int | str | Any], Any, NoReturn]:
        """Listen for commands coming to the server."""

class PubSub:
    """
    PubSub provides publish, subscribe and listen support to Redis channels.

    After subscribing to one or more channels, the listen() method will block
    until a message arrives on one of the subscribed channels. That message
    will be returned and it's safe to start listening again.
    """

    PUBLISH_MESSAGE_TYPES = ...
    UNSUBSCRIBE_MESSAGE_TYPES = ...
    HEALTH_CHECK_MESSAGE = ...
    def __init__(
        self,
        connection_pool,
        shard_hint=...,
        ignore_subscribe_messages: bool = ...,
        encoder: Encoder | None = ...,
        push_handler_func: None | Callable[[str], None] = ...,
    ) -> None: ...
    def __enter__(self) -> PubSub: ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...
    def __del__(self) -> None: ...
    def reset(self) -> None: ...
    def close(self) -> None: ...
    def on_connect(self, connection) -> None:
        """Re-subscribe to any channels and patterns previously subscribed to"""

    @property
    def subscribed(self) -> bool:
        """Indicates if there are subscriptions to any channels or patterns"""

    def execute_command(self, *args):  # -> None:
        """Execute a publish/subscribe command"""

    def clean_health_check_responses(self) -> None:
        """
        If any health check responses are present, clean them
        """

    def parse_response(self, block=..., timeout=...):  # -> None:
        """Parse the response from a publish/subscribe command"""

    def is_health_check_response(self, response) -> bool:
        """
        Check if the response is a health check response.
        If there are no subscriptions redis responds to PING command with a
        bulk response, instead of a multi-bulk with "pong" and the response.
        """

    def check_health(self) -> None: ...
    def psubscribe(self, *args, **kwargs):  # -> None:
        """
        Subscribe to channel patterns. Patterns supplied as keyword arguments
        expect a pattern name as the key and a callable as the value. A
        pattern's callable will be invoked automatically when a message is
        received on that pattern rather than producing a message via
        ``listen()``.
        """

    def punsubscribe(self, *args):  # -> None:
        """
        Unsubscribe from the supplied patterns. If empty, unsubscribe from
        all patterns.
        """

    def subscribe(self, *args, **kwargs):  # -> None:
        """
        Subscribe to channels. Channels supplied as keyword arguments expect
        a channel name as the key and a callable as the value. A channel's
        callable will be invoked automatically when a message is received on
        that channel rather than producing a message via ``listen()`` or
        ``get_message()``.
        """

    def unsubscribe(self, *args):  # -> None:
        """
        Unsubscribe from the supplied channels. If empty, unsubscribe from
        all channels
        """

    def ssubscribe(self, *args, target_node=..., **kwargs):  # -> None:
        """
        Subscribes the client to the specified shard channels.
        Channels supplied as keyword arguments expect a channel name as the key
        and a callable as the value. A channel's callable will be invoked automatically
        when a message is received on that channel rather than producing a message via
        ``listen()`` or ``get_sharded_message()``.
        """

    def sunsubscribe(self, *args, target_node=...):  # -> None:
        """
        Unsubscribe from the supplied shard_channels. If empty, unsubscribe from
        all shard_channels
        """

    def listen(self):  # -> Generator[dict[str, str | bytes | Any] | dict[str, str | bytes | Any | None], Any, None]:
        """Listen for messages on channels this client has been subscribed to"""

    def get_message(
        self, ignore_subscribe_messages: bool = ..., timeout: float = ...
    ):  # -> dict[str, str | bytes | Any] | dict[str, str | bytes | Any | None] | None:
        """
        Get the next message if one is available, otherwise None.

        If timeout is specified, the system will wait for `timeout` seconds
        before returning. Timeout should be specified as a floating point
        number, or None, to wait indefinitely.
        """

    get_sharded_message = ...
    def ping(self, message: str | None = ...) -> bool:
        """
        Ping the Redis server
        """

    def handle_message(
        self, response, ignore_subscribe_messages=...
    ):  # -> dict[str, str | bytes | Any] | dict[str, str | bytes | Any | None] | None:
        """
        Parses a pub/sub message. If the channel or pattern was subscribed to
        with a message handler, the handler is invoked instead of a parsed
        message being returned.
        """

    def run_in_thread(
        self, sleep_time: float = ..., daemon: bool = ..., exception_handler: Callable | None = ...
    ) -> PubSubWorkerThread: ...

class PubSubWorkerThread(threading.Thread):
    def __init__(
        self,
        pubsub,
        sleep_time: float,
        daemon: bool = ...,
        exception_handler: Callable[[Exception, PubSub, PubSubWorkerThread], None] | None = ...,
    ) -> None: ...
    def run(self) -> None: ...
    def stop(self) -> None: ...

class Pipeline(Redis):
    """
    Pipelines provide a way to transmit multiple commands to the Redis server
    in one transmission.  This is convenient for batch processing, such as
    saving all the values in a list to Redis.

    All commands executed within a pipeline are wrapped with MULTI and EXEC
    calls. This guarantees all commands executed in the pipeline will be
    executed atomically.

    Any command raising an exception does *not* halt the execution of
    subsequent commands in the pipeline. Instead, the exception is caught
    and its instance is placed into the response list returned by execute().
    Code iterating over the response list should be able to deal with an
    instance of an exception as a potential value. In general, these will be
    ResponseError exceptions, such as those raised when issuing a command
    on a key of a different datatype.
    """

    UNWATCH_COMMANDS = ...
    def __init__(self, connection_pool, response_callbacks, transaction, shard_hint) -> None: ...
    def __enter__(self) -> Pipeline: ...
    def __exit__(self, exc_type, exc_value, traceback):  # -> None:
        ...
    def __del__(self):  # -> None:
        ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool:
        """Pipeline instances should always evaluate to True"""

    def reset(self) -> None: ...
    def close(self) -> None:
        """Close the pipeline"""

    def multi(self) -> None:
        """
        Start a transactional block of the pipeline after WATCH commands
        are issued. End the transactional block with `execute`.
        """

    def execute_command(self, *args, **kwargs):  # -> Any | Pipeline:
        ...
    def immediate_execute_command(self, *args, **options):  # -> Any:
        """
        Execute a command immediately, but don't auto-retry on a
        ConnectionError if we're already WATCHing a variable. Used when
        issuing WATCH or subsequent commands retrieving their values but before
        MULTI is called.
        """

    def pipeline_execute_command(self, *args, **options) -> Pipeline:
        """
        Stage a command to be executed when execute() is next called

        Returns the current Pipeline object back so commands can be
        chained together, such as:

        pipe = pipe.set('foo', 'bar').incr('baz').decr('bang')

        At some other point, you can then run: pipe.execute(),
        which will execute all commands queued in the pipe.
        """

    def raise_first_error(self, commands, response):  # -> None:
        ...
    def annotate_exception(self, exception, number, command):  # -> None:
        ...
    def parse_response(self, connection, command_name, **options): ...
    def load_scripts(self):  # -> None:
        ...
    def execute(self, raise_on_error=...):  # -> list[Any] | Any:
        """Execute all the commands in the current pipeline"""

    def discard(self):  # -> None:
        """
        Flushes all previously queued commands
        See: https://redis.io/commands/DISCARD
        """

    def watch(self, *names):  # -> Any | Pipeline:
        """Watches the values at keys ``names``"""

    def unwatch(self) -> bool:
        """Unwatches all previously specified keys"""
