"""
This type stub file was generated by pyright.
"""

class Edge:
    """
    An edge connecting two nodes.
    """

    def __init__(self, src_node, relation, dest_node, edge_id=..., properties=...) -> None:
        """
        Create a new edge.
        """

    def to_string(self):  # -> LiteralString | Literal['']:
        ...
    def __eq__(self, rhs) -> bool: ...
