"""
This type stub file was generated by pyright.
"""

class ProfileStats:
    """
    ProfileStats, runtime execution statistics of operation.
    """

    def __init__(self, records_produced, execution_time) -> None: ...

class Operation:
    """
    Operation, single operation within execution plan.
    """

    def __init__(self, name, args=..., profile_stats=...) -> None:
        """
        Create a new operation.

        Args:
            name: string that represents the name of the operation
            args: operation arguments
            profile_stats: profile statistics

        """

    def append_child(self, child):  # -> Self:
        ...
    def child_count(self):  # -> int:
        ...
    def __eq__(self, o: object) -> bool: ...

class ExecutionPlan:
    """
    ExecutionPlan, collection of operations.
    """

    def __init__(self, plan) -> None:
        """
        Create a new execution plan.

        Args:
            plan: array of strings that represents the collection operations
                  the output from GRAPH.EXPLAIN

        """

    def __eq__(self, o: object) -> bool:
        """Compares two execution plans

        Return: True if the two plans are equal False otherwise
        """
