"""
This type stub file was generated by pyright.
"""

class Node:
    """
    A node within the graph.
    """

    def __init__(self, node_id=..., alias=..., label=..., properties=...) -> None:
        """
        Create a new node.
        """

    def to_string(self):  # -> LiteralString | Literal['']:
        ...
    def __eq__(self, rhs) -> bool: ...
