"""
This type stub file was generated by pyright.
"""

import abc

class AbstractMetricsReporter(abc.ABC):
    """
    An abstract class to allow things to listen as new metrics
    are created so they can be reported.
    """

    @abc.abstractmethod
    def init(self, metrics):  # -> None:
        """
        This is called when the reporter is first registered
        to initially register all existing metrics

        Arguments:
            metrics (list of KafkaMetric): All currently existing metrics

        """
        ...

    @abc.abstractmethod
    def metric_change(self, metric):  # -> None:
        """
        This is called whenever a metric is updated or added

        Arguments:
            metric (KafkaMetric)

        """
        ...

    @abc.abstractmethod
    def metric_removal(self, metric):  # -> None:
        """
        This is called whenever a metric is removed

        Arguments:
            metric (KafkaMetric)

        """
        ...

    @abc.abstractmethod
    def configure(self, configs):  # -> None:
        """
        Configure this class with the given key-value pairs

        Arguments:
            configs (dict of {str, ?})

        """
        ...

    @abc.abstractmethod
    def close(self):  # -> None:
        """Called when the metrics repository is closed."""
        ...
