"""
This type stub file was generated by pyright.
"""

import abc

class AbstractStat(abc.ABC):
    """
    An AbstractStat is a quantity such as average, max, etc that is computed
    off the stream of updates to a sensor
    """

    @abc.abstractmethod
    def record(self, config, value, time_ms):  # -> None:
        """
        Record the given value

        Arguments:
            config (MetricConfig): The configuration to use for this metric
            value (float): The value to record
            timeMs (int): The POSIX time in milliseconds this value occurred

        """
        ...
