"""modified password hash

Revision ID: 8281c54a7678
Revises: b915779ecba8
Create Date: 2024-09-12 20:59:27.620748

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8281c54a7678"
down_revision: str | None = "b915779ecba8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user" ALTER COLUMN password TYPE JSON USING password::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "password", existing_type=sa.JSON(), type_=sa.VARCHAR(length=60), existing_nullable=False)
    # ### end Alembic commands ###
