"""FK cascade and History index

Revision ID: b6cf44301fba
Revises: 8281c54a7678
Create Date: 2024-09-16 03:54:37.149859

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b6cf44301fba"
down_revision: str | None = "8281c54a7678"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("history_user_id_fkey1", "history", type_="foreignkey")
    op.create_foreign_key("history_user_id_fkey", "history", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_index("_idx_history_2024", "history_2024", ["user_id", "action"], unique=False)
    op.create_index("_idx_history_2025", "history_2025", ["user_id", "action"], unique=False)
    op.create_index("_idx_history_2026", "history_2026", ["user_id", "action"], unique=False)
    op.create_index("_idx_history_2027", "history_2027", ["user_id", "action"], unique=False)
    op.drop_constraint("user_right_user_id_fkey", "user_right", type_="foreignkey")
    op.drop_constraint("user_right_right_id_fkey", "user_right", type_="foreignkey")
    op.create_foreign_key("user_right_user_id_fkey", "user_right", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key("user_right_right_id_fkey", "user_right", "right", ["right_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_right_right_id_fkey", "user_right", type_="foreignkey")
    op.drop_constraint("user_right_user_id_fkey", "user_right", type_="foreignkey")
    op.create_foreign_key("user_right_right_id_fkey", "user_right", "right", ["right_id"], ["id"])
    op.create_foreign_key("user_right_user_id_fkey", "user_right", "user", ["user_id"], ["id"])
    op.drop_index("_idx_history_2027", table_name="history_2027")
    op.drop_index("_idx_history_2026", table_name="history_2026")
    op.drop_index("_idx_history_2025", table_name="history_2025")
    op.drop_index("_idx_history_2024", table_name="history_2024")
    op.drop_constraint("history_user_id_fkey", "history", type_="foreignkey")
    op.create_foreign_key("history_user_id_fkey1", "history", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###
