"""User.email_confirmed

Revision ID: de722380ea20
Revises: b6cf44301fba
Create Date: 2024-11-06 18:09:38.079906

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "de722380ea20"
down_revision: str | None = "b6cf44301fba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email_confirmed", sa.Boolean(), server_default="False", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "email_confirmed")
    # ### end Alembic commands ###
