"""
This type stub file was generated by pyright.
"""

from beanie.odm.documents import Document

def free_fall_migration(document_models: list[type[Document]]):  # -> type[FreeFallMigrationController]:
    ...
