"""
This type stub file was generated by pyright.
"""

from kafka.protocol.struct import Struct

class ConsumerProtocolMemberMetadata(Struct):
    SCHEMA = ...

class ConsumerProtocolMemberAssignment(Struct):
    SCHEMA = ...
    def partitions(self):  # -> list[TopicPartition]:
        ...

class ConsumerProtocol:
    PROTOCOL_TYPE = ...
    ASSIGNMENT_STRATEGIES = ...
    METADATA = ConsumerProtocolMemberMetadata
    ASSIGNMENT = ConsumerProtocolMemberAssignment
