"""
This type stub file was generated by pyright.
"""

class RedisModuleCommands:
    """This class contains the wrapper functions to bring supported redis
    modules into the command namespace.
    """

    def json(self, encoder=..., decoder=...):  # -> JSON:
        """Access the json namespace, providing support for redis json."""

    def ft(self, index_name=...):  # -> Search:
        """Access the search namespace, providing support for redis search."""

    def ts(self):  # -> TimeSeries:
        """Access the timeseries namespace, providing support for
        redis timeseries data.
        """

    def bf(self):  # -> BFBloom:
        """Access the bloom namespace."""

    def cf(self):  # -> CFBloom:
        """Access the bloom namespace."""

    def cms(self):  # -> CMSBloom:
        """Access the bloom namespace."""

    def topk(self):  # -> TOPKBloom:
        """Access the bloom namespace."""

    def tdigest(self):  # -> TDigestBloom:
        """Access the bloom namespace."""

    def graph(self, index_name=...):  # -> Graph:
        """Access the graph namespace, providing support for
        redis graph data.
        """

class AsyncRedisModuleCommands(RedisModuleCommands):
    def ft(self, index_name=...):  # -> AsyncSearch:
        """Access the search namespace, providing support for redis search."""

    def graph(self, index_name=...):  # -> AsyncGraph:
        """Access the graph namespace, providing support for
        redis graph data.
        """
