"""
This type stub file was generated by pyright.
"""

from typing import Literal, TypeAlias

CodecNoneT: TypeAlias = Literal[0]
CodecGzipT: TypeAlias = Literal[1]
CodecSnappyT: TypeAlias = Literal[2]
CodecLz4T: TypeAlias = Literal[3]
CodecZstdT: TypeAlias = Literal[4]
CodecMaskT: TypeAlias = Literal[7]
DefaultCompressionTypeT: TypeAlias = CodecGzipT | CodecLz4T | CodecNoneT | CodecSnappyT | CodecZstdT
LegacyCompressionTypeT: TypeAlias = CodecGzipT | CodecLz4T | CodecSnappyT | CodecNoneT
