"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Self

_SCHEMA = ...

@dataclass(frozen=True)
class ControlRecord:
    __slots__ = ...
    version: int
    type_: int
    def __eq__(self, other: object) -> bool: ...
    @classmethod
    def parse(cls, data: bytes) -> Self: ...

ABORT_MARKER = ...
COMMIT_MARKER = ...
