"""
This type stub file was generated by pyright.
"""

from clickhouse_connect.datatypes.base import ClickHouseType, TypeDef

class String(ClickHouseType):
    valid_formats = ...

class FixedString(ClickHouseType):
    valid_formats = ...
    def __init__(self, type_def: TypeDef) -> None: ...
    @property
    def np_type(self):  # -> str:
        ...
