"""
This type stub file was generated by pyright.
"""

from collections.abc import MutableMapping

from opentelemetry.util import types

_VALID_ATTR_VALUE_TYPES = ...
_logger = ...

class BoundedAttributes(MutableMapping):
    """An ordered dict with a fixed max capacity.

    Oldest elements are dropped when the dict is full and a new element is
    added.
    """

    def __init__(
        self,
        maxlen: int | None = ...,
        attributes: types.Attributes = ...,
        immutable: bool = ...,
        max_value_len: int | None = ...,
    ) -> None: ...
    def __getitem__(self, key: str) -> types.AttributeValue: ...
    def __setitem__(self, key: str, value: types.AttributeValue) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self):  # -> Iterator[str]:
        ...
    def __len__(self) -> int: ...
    def copy(self):  # -> OrderedDict[str, AttributeValue]:
        ...
