"""
This type stub file was generated by pyright.
"""

from functools import cache

"""
Debug Toolbar middleware
"""

def show_toolbar(request):  # -> bool:
    """
    Default function to determine whether to show the toolbar on a given page.
    """

@cache
def get_show_toolbar():  # -> Any | set[str] | int | bool | tuple[str, str, str, str, str, str, str, str, str, str] | tuple[str, str] | list[Any] | None:
    ...

class DebugToolbarMiddleware:
    """
    Middleware to set up Debug Toolbar on incoming request and render toolbar
    on outgoing response.
    """

    def __init__(self, get_response) -> None: ...
    def __call__(self, request):  # -> Any:
        ...
    @staticmethod
    def get_headers(request, panels):  # -> dict[Any, Any]:
        ...
