"""
This type stub file was generated by pyright.
"""

class Percentile:
    def __init__(self, metric_name, percentile) -> None: ...
    @property
    def name(self):  # -> Any:
        ...
    @property
    def percentile(self):  # -> float:
        ...
