"""
This type stub file was generated by pyright.
"""

import datetime
from datetime import timedelta
from typing import Any

from pydantic import BaseModel

class CachedItem(BaseModel):
    timestamp: datetime.datetime = ...
    value: Any

class LRUCache:
    def __init__(self, capacity: int, expiration_time: timedelta) -> None: ...
    def get(self, key) -> CachedItem | None: ...
    def set(self, key, value) -> None: ...
    @staticmethod
    def create_key(*args):  # -> str:
        ...
