"""
This type stub file was generated by pyright.
"""

from enum import Enum, StrEnum

class SortDirection(int, Enum):
    """
    Sorting directions
    """

    ASCENDING = ...
    DESCENDING = ...

class InspectionStatuses(StrEnum):
    """
    Statuses of the collection inspection
    """

    FAIL = ...
    OK = ...
