# Generated by Django 4.2.11 on 2024-09-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(model_name="user", name="is_staff", field=models.BooleanField(default=False)),
    ]
