"""
This type stub file was generated by pyright.
"""

from enum import StrEnum

class ModelType(StrEnum):
    Document = ...
    View = ...
    UnionDoc = ...

class DetectionInterface:
    @classmethod
    def get_model_type(cls) -> ModelType: ...
