"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod

from beanie.odm.settings.base import ItemSettings
from motor.motor_asyncio import AsyncIOMotorCollection

class OtherGettersInterface:
    @classmethod
    @abstractmethod
    def get_settings(cls) -> ItemSettings: ...
    @classmethod
    def get_motor_collection(cls) -> AsyncIOMotorCollection: ...
    @classmethod
    def get_collection_name(cls):  # -> str | None:
        ...
    @classmethod
    def get_bson_encoders(cls):  # -> Dict[Any, Any]:
        ...
    @classmethod
    def get_link_fields(cls):  # -> None:
        ...
