# Generated by Django 4.2.11 on 2024-06-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_filmwork_file_path"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genrefilmwork", options={"verbose_name": "Genre", "verbose_name_plural": "Genres"}
        ),
        migrations.AlterModelOptions(
            name="personfilmwork", options={"verbose_name": "Person", "verbose_name_plural": "Persons"}
        ),
        migrations.AlterField(
            model_name="filmwork", name="created", field=models.DateTimeField(auto_now_add=True, verbose_name="created")
        ),
        migrations.AlterField(
            model_name="filmwork", name="modified", field=models.DateTimeField(auto_now=True, verbose_name="modified")
        ),
        migrations.AlterField(
            model_name="genre", name="created", field=models.DateTimeField(auto_now_add=True, verbose_name="created")
        ),
        migrations.AlterField(
            model_name="genre", name="modified", field=models.DateTimeField(auto_now=True, verbose_name="modified")
        ),
        migrations.AlterField(
            model_name="person", name="created", field=models.DateTimeField(auto_now_add=True, verbose_name="created")
        ),
        migrations.AlterField(
            model_name="person", name="modified", field=models.DateTimeField(auto_now=True, verbose_name="modified")
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                choices=[("actor", "actor"), ("writer", "writer"), ("director", "director")],
                default="actor",
                verbose_name="role",
            ),
        ),
    ]
