# Generated by Django 4.2.11 on 2024-09-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_genrefilmwork_film_work_genre_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="genrefilmwork",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
    ]
