# Generated by Django 4.2.11 on 2024-09-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_alter_filmwork_description_alter_genre_description_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="genrefilmwork", name="film_work_genre_idx"),
        migrations.RemoveConstraint(model_name="personfilmwork", name="film_work_person_role_idx"),
        migrations.AlterField(
            model_name="filmwork",
            name="creation_date",
            field=models.DateField(blank=True, null=True, verbose_name="creation_date"),
        ),
        migrations.AlterUniqueTogether(name="genrefilmwork", unique_together={("film_work", "genre")}),
        migrations.AlterUniqueTogether(name="personfilmwork", unique_together={("film_work", "person", "role")}),
    ]
