"""
This type stub file was generated by pyright.
"""

from opentelemetry.context.context import Context
from opentelemetry.trace.span import Span

SPAN_KEY = ...
_SPAN_KEY = ...

def set_span_in_context(span: Span, context: Context | None = ...) -> Context:
    """Set the span in the given context.

    Args:
        span: The Span to set.
        context: a Context object. if one is not passed, the
            default current context is used instead.

    """

def get_current_span(context: Context | None = ...) -> Span:
    """Retrieve the current span.

    Args:
        context: A Context object. If one is not passed, the
            default current context is used instead.

    Returns:
        The Span set in the context if it exists. INVALID_SPAN otherwise.

    """
