"""
This type stub file was generated by pyright.
"""

import decimal
import typing
from typing import Annotated

import bson
import pydantic

DecimalAnnotation: typing.TypeAlias = Annotated[
    decimal.Decimal,
    pydantic.BeforeValidator(lambda v: v.to_decimal() if isinstance(v, bson.Decimal128) else v),
]
