"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from collections.abc import Mapping
from collections.abc import Mapping as MappingType
from typing import Any

class BaseOperator(Mapping):
    """
    Base operator.
    """

    @property
    @abstractmethod
    def query(self) -> MappingType[str, Any]: ...
    def __getitem__(self, item: str):  # -> Any:
        ...
    def __iter__(self):  # -> Iterator[str]:
        ...
    def __len__(self):  # -> int:
        ...
    def __repr__(self):  # -> str:
        ...
    def __copy__(self):  # -> Mapping[str, Any]:
        ...
    def __deepcopy__(self, memodict: dict[str, Any] = ...):  # -> Mapping[str, Any]:
        ...
    def copy(self):  # -> Self:
        ...
