"""init

Revision ID: 1ea0f4e51f6c
Revises:
Create Date: 2024-11-24 13:32:04.623319

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1ea0f4e51f6c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("login", sa.String(length=60), nullable=False),
        sa.Column("fio", sa.String(length=60), nullable=True),
        sa.Column("email", sa.String(length=60), nullable=False),
        sa.Column("email_confirmed", sa.Boolean(), server_default="False", nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_index(op.f("ix_profile_login"), "profile", ["login"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profile_login"), table_name="profile")
    op.drop_table("profile")
    # ### end Alembic commands ###
