"""
This type stub file was generated by pyright.
"""

import abc

class Serializer:
    __meta__ = abc.ABCMeta
    def __init__(self, **config) -> None: ...
    @abc.abstractmethod
    def serialize(self, topic, value):  # -> None:
        ...
    def close(self):  # -> None:
        ...

class Deserializer:
    __meta__ = abc.ABCMeta
    def __init__(self, **config) -> None: ...
    @abc.abstractmethod
    def deserialize(self, topic, bytes_):  # -> None:
        ...
    def close(self):  # -> None:
        ...
