"""
This type stub file was generated by pyright.
"""

import bson
from beanie.odm.utils.pydantic import IS_PYDANTIC_V2

if IS_PYDANTIC_V2:
    BsonBinary = ...
else:
    class BsonBinary(bson.Binary):
        @classmethod
        def __get_validators__(cls):  # -> Generator[Callable[..., Binary], Any, None]:
            ...
