"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from beanie.odm.documents import Document

if TYPE_CHECKING: ...

def get_dict(document: Document, to_db: bool = ..., exclude: set[str] | None = ..., keep_nulls: bool = ...):  # -> Any:
    ...
def get_nulls(document: Document, exclude: set[str] | None = ...):  # -> dict[Any, Any]:
    ...
def get_top_level_nones(document: Document, exclude: set[str] | None = ...):  # -> dict[Any, Any]:
    ...
def filter_none(d):  # -> dict[Any, Any]:
    ...
