"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING, Any

from beanie.odm.documents import Document
from pydantic import BaseModel

if TYPE_CHECKING: ...

def merge_models(left: BaseModel, right: BaseModel) -> None:
    """
    Merge two models
    :param left: left model
    :param right: right model
    :return: None
    """

def apply_changes(changes: dict[str, Any], target: BaseModel | dict[str, Any]):  # -> None:
    ...
def save_state(item: BaseModel):  # -> None:
    ...
def parse_obj(model: type[BaseModel | Document], data: Any, lazy_parse: bool = ...) -> BaseModel: ...
