"""
This type stub file was generated by pyright.
"""

from typing import TypeVar

from pydantic import BaseModel

ProjectionModelType = TypeVar("ProjectionModelType", bound=BaseModel)

def get_projection(model: type[ProjectionModelType]) -> dict[str, int] | None: ...
