"""
This type stub file was generated by pyright.
"""

from typing import Any

def extract_id_class(annotation) -> type[Any]: ...
def get_index_attributes(field) -> tuple[int, dict[str, Any]] | None:
    """Gets the index attributes from the field, if it is indexed.

    :param field: The field to get the index attributes from.

    :return: The index attributes, if the field is indexed. Otherwise, None.
    """
