"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING, TypeVar

from opentelemetry.metrics import MeterProvider
from opentelemetry.trace import TracerProvider

if TYPE_CHECKING: ...
Provider = TypeVar("Provider", TracerProvider, MeterProvider)
logger = ...
