"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, Generic, TypeVar

from beanie.odm.documents import DocType
from beanie.odm.interfaces.clone import CloneInterface
from beanie.odm.interfaces.session import SessionMethods
from beanie.odm.queries.cursor import BaseCursorQuery
from motor.core import AgnosticCommandCursor
from pydantic import BaseModel

if TYPE_CHECKING: ...
AggregationProjectionType = TypeVar("AggregationProjectionType")

class AggregationQuery(
    BaseCursorQuery[AggregationProjectionType], SessionMethods, CloneInterface, Generic[AggregationProjectionType]
):
    """
    Aggregation Query
    """

    def __init__(
        self,
        document_model: type[DocType],
        aggregation_pipeline: list[Mapping[str, Any]],
        find_query: Mapping[str, Any],
        projection_model: type[BaseModel] | None = ...,
        ignore_cache: bool = ...,
        **pymongo_kwargs,
    ) -> None: ...
    def get_aggregation_pipeline(self) -> list[Mapping[str, Any]]: ...
    @property
    def motor_cursor(self) -> AgnosticCommandCursor: ...
    def get_projection_model(self) -> type[BaseModel] | None: ...
