"""
This type stub file was generated by pyright.
"""

from beanie.odm.operators.update import BaseUpdateOperator

class BaseUpdateGeneralOperator(BaseUpdateOperator):
    operator = ...
    def __init__(self, expression) -> None: ...
    @property
    def query(self):  # -> dict[str, Any]:
        ...

class Set(BaseUpdateGeneralOperator):
    """
    `$set` update query operator

    Example:
    ```python
    class Sample(Document):
        one: int

    Set({Sample.one: 2})
    ```

    Will return query object like

    ```python
    {"$set": {"one": 2}}
    ```

    MongoDB doc:
    <https://docs.mongodb.com/manual/reference/operator/update/set/>

    """

    operator = ...

class SetRevisionId:
    """
    `$set` update query operator

    Example:
    ```python
    class Sample(Document):
        one: int

    Set({Sample.one: 2})
    ```

    Will return query object like

    ```python
    {"$set": {"one": 2}}
    ```

    MongoDB doc:
    <https://docs.mongodb.com/manual/reference/operator/update/set/>

    """

    def __init__(self, revision_id) -> None: ...
    @property
    def query(self):  # -> dict[str, dict[str, Any]]:
        ...

class CurrentDate(BaseUpdateGeneralOperator):
    """
    `$currentDate` update query operator

    Example:
    ```python
    class Sample(Document):
        ts: datetime

    CurrentDate({Sample.ts: True})
    ```

    Will return query object like

    ```python
    {"$currentDate": {"ts": True}}
    ```

    MongoDB doc:
    <https://docs.mongodb.com/manual/reference/operator/update/currentDate/>

    """

    operator = ...

class Inc(BaseUpdateGeneralOperator):
    """
    `$inc` update query operator

    Example:
    ```python
    class Sample(Document):
        one: int

    Inc({Sample.one: 2})
    ```

    Will return query object like

    ```python
    {"$inc": {"one": 2}}
    ```

    MongoDB doc:
    <https://docs.mongodb.com/manual/reference/operator/update/inc/>

    """

    operator = ...

class Min(BaseUpdateGeneralOperator):
    """
    `$min` update query operator

    Example:
    ```python
    class Sample(Document):
        one: int

    Min({Sample.one: 2})
    ```

    Will return query object like

    ```python
    {"$min": {"one": 2}}
    ```

    MongoDB doc:
    <https://docs.mongodb.com/manual/reference/operator/update/min/>

    """

    operator = ...

class Max(BaseUpdateGeneralOperator):
    """
    `$max` update query operator

    Example:
    ```python
    class Sample(Document):
        one: int

    Max({Sample.one: 2})
    ```

    Will return query object like

    ```python
    {"$max": {"one": 2}}
    ```

    MongoDB doc:
    <https://docs.mongodb.com/manual/reference/operator/update/max/>

    """

    operator = ...

class Mul(BaseUpdateGeneralOperator):
    """
    `$mul` update query operator

    Example:
    ```python
    class Sample(Document):
        one: int

    Mul({Sample.one: 2})
    ```

    Will return query object like

    ```python
    {"$mul": {"one": 2}}
    ```

    MongoDB doc:
    <https://docs.mongodb.com/manual/reference/operator/update/mul/>

    """

    operator = ...

class Rename(BaseUpdateGeneralOperator):
    """
    `$rename` update query operator

    MongoDB doc:
    <https://docs.mongodb.com/manual/reference/operator/update/rename/>
    """

    operator = ...

class SetOnInsert(BaseUpdateGeneralOperator):
    """
    `$setOnInsert` update query operator

    MongoDB doc:
    <https://docs.mongodb.com/manual/reference/operator/update/setOnInsert/>
    """

    operator = ...

class Unset(BaseUpdateGeneralOperator):
    """
    `$unset` update query operator

    MongoDB doc:
    <https://docs.mongodb.com/manual/reference/operator/update/unset/>
    """

    operator = ...
