"""
This type stub file was generated by pyright.
"""

from clickhouse_connect.driver import create_async_client, create_client

driver_name = "clickhousedb"
get_client = create_client
get_async_client = create_async_client
