"""
This type stub file was generated by pyright.
"""

from beanie.migrations.controllers.free_fall import free_fall_migration
from beanie.migrations.controllers.iterative import iterative_migration
from beanie.odm.actions import (
    After,
    Before,
    Delete,
    Insert,
    Replace,
    Save,
    SaveChanges,
    Update,
    ValidateOnSave,
    after_event,
    before_event,
)
from beanie.odm.bulk import BulkWriter
from beanie.odm.custom_types import DecimalAnnotation
from beanie.odm.custom_types.bson.binary import BsonBinary
from beanie.odm.documents import Document, DocumentWithSoftDelete, MergeStrategy
from beanie.odm.enums import SortDirection
from beanie.odm.fields import BackLink, BeanieObjectId, DeleteRules, Indexed, Link, PydanticObjectId, WriteRules
from beanie.odm.queries.update import UpdateResponse
from beanie.odm.settings.timeseries import Granularity, TimeSeriesConfig
from beanie.odm.union_doc import UnionDoc
from beanie.odm.utils.init import init_beanie
from beanie.odm.views import View

__version__ = ...
__all__ = [
    "After",
    "BackLink",
    "BeanieObjectId",
    "Before",
    "BsonBinary",
    "BulkWriter",
    "DecimalAnnotation",
    "Delete",
    "DeleteRules",
    "Document",
    "DocumentWithSoftDelete",
    "Granularity",
    "Indexed",
    "Insert",
    "Link",
    "MergeStrategy",
    "PydanticObjectId",
    "Replace",
    "Save",
    "SaveChanges",
    "SortDirection",
    "TimeSeriesConfig",
    "UnionDoc",
    "Update",
    "UpdateResponse",
    "ValidateOnSave",
    "View",
    "WriteRules",
    "after_event",
    "before_event",
    "free_fall_migration",
    "init_beanie",
    "iterative_migration",
]
