"""
This type stub file was generated by pyright.
"""

import io
from abc import ABC, abstractmethod
from collections.abc import Generator, Iterable, Sequence
from datetime import tzinfo
from typing import Any, BinaryIO

from clickhouse_connect.datatypes.base import ClickHouseType
from clickhouse_connect.driver.common import StreamContext
from clickhouse_connect.driver.external import ExternalData
from clickhouse_connect.driver.insert import InsertContext
from clickhouse_connect.driver.query import QueryContext, QueryResult
from clickhouse_connect.driver.summary import QuerySummary

logger = ...
arrow_str_setting = ...

class Client(ABC):
    """
    Base ClickHouse Connect client
    """

    compression: str = ...
    write_compression: str = ...
    protocol_version = ...
    valid_transport_settings = ...
    optional_transport_settings = ...
    database = ...
    max_error_message = ...
    apply_server_timezone = ...
    show_clickhouse_errors = ...
    def __init__(
        self,
        database: str,
        query_limit: int,
        uri: str,
        query_retries: int,
        server_host_name: str | None,
        apply_server_timezone: str | bool | None,
        show_clickhouse_errors: bool | None,
    ) -> None:
        """
        Shared initialization of ClickHouse Connect client
        :param database: database name
        :param query_limit: default LIMIT for queries
        :param uri: uri for error messages
        """

    @abstractmethod
    def set_client_setting(self, key, value):  # -> None:
        """
        Set a clickhouse setting for the client after initialization.  If a setting is not recognized by ClickHouse,
        or the setting is identified as "read_only", this call will either throw a Programming exception or attempt
        to send the setting anyway based on the common setting 'invalid_setting_action'
        :param key: ClickHouse setting name
        :param value: ClickHouse setting value
        """
        ...

    @abstractmethod
    def get_client_setting(self, key) -> str | None:
        """
        :param key: The setting key
        :return: The string value of the setting, if it exists, or None
        """
        ...

    def query(
        self,
        query: str | None = ...,
        parameters: Sequence | dict[str, Any] | None = ...,
        settings: dict[str, Any] | None = ...,
        query_formats: dict[str, str] | None = ...,
        column_formats: dict[str, str | dict[str, str]] | None = ...,
        encoding: str | None = ...,
        use_none: bool | None = ...,
        column_oriented: bool | None = ...,
        use_numpy: bool | None = ...,
        max_str_len: int | None = ...,
        context: QueryContext = ...,
        query_tz: str | tzinfo | None = ...,
        column_tzs: dict[str, str | tzinfo] | None = ...,
        external_data: ExternalData | None = ...,
    ) -> QueryResult:
        """
        Main query method for SELECT, DESCRIBE and other SQL statements that return a result matrix.  For
        parameters, see the create_query_context method
        :return: QueryResult -- data and metadata from response
        """

    def query_column_block_stream(
        self,
        query: str | None = ...,
        parameters: Sequence | dict[str, Any] | None = ...,
        settings: dict[str, Any] | None = ...,
        query_formats: dict[str, str] | None = ...,
        column_formats: dict[str, str | dict[str, str]] | None = ...,
        encoding: str | None = ...,
        use_none: bool | None = ...,
        context: QueryContext = ...,
        query_tz: str | tzinfo | None = ...,
        column_tzs: dict[str, str | tzinfo] | None = ...,
        external_data: ExternalData | None = ...,
    ) -> StreamContext:
        """
        Variation of main query method that returns a stream of column oriented blocks. For
        parameters, see the create_query_context method.
        :return: StreamContext -- Iterable stream context that returns column oriented blocks
        """

    def query_row_block_stream(
        self,
        query: str | None = ...,
        parameters: Sequence | dict[str, Any] | None = ...,
        settings: dict[str, Any] | None = ...,
        query_formats: dict[str, str] | None = ...,
        column_formats: dict[str, str | dict[str, str]] | None = ...,
        encoding: str | None = ...,
        use_none: bool | None = ...,
        context: QueryContext = ...,
        query_tz: str | tzinfo | None = ...,
        column_tzs: dict[str, str | tzinfo] | None = ...,
        external_data: ExternalData | None = ...,
    ) -> StreamContext:
        """
        Variation of main query method that returns a stream of row oriented blocks. For
        parameters, see the create_query_context method.
        :return: StreamContext -- Iterable stream context that returns blocks of rows
        """

    def query_rows_stream(
        self,
        query: str | None = ...,
        parameters: Sequence | dict[str, Any] | None = ...,
        settings: dict[str, Any] | None = ...,
        query_formats: dict[str, str] | None = ...,
        column_formats: dict[str, str | dict[str, str]] | None = ...,
        encoding: str | None = ...,
        use_none: bool | None = ...,
        context: QueryContext = ...,
        query_tz: str | tzinfo | None = ...,
        column_tzs: dict[str, str | tzinfo] | None = ...,
        external_data: ExternalData | None = ...,
    ) -> StreamContext:
        """
        Variation of main query method that returns a stream of row oriented blocks. For
        parameters, see the create_query_context method.
        :return: StreamContext -- Iterable stream context that returns blocks of rows
        """

    @abstractmethod
    def raw_query(
        self,
        query: str,
        parameters: Sequence | dict[str, Any] | None = ...,
        settings: dict[str, Any] | None = ...,
        fmt: str = ...,
        use_database: bool = ...,
        external_data: ExternalData | None = ...,
    ) -> bytes:
        """
        Query method that simply returns the raw ClickHouse format bytes
        :param query: Query statement/format string
        :param parameters: Optional dictionary used to format the query
        :param settings: Optional dictionary of ClickHouse settings (key/string values)
        :param fmt: ClickHouse output format
        :param use_database  Send the database parameter to ClickHouse so the command will be executed in the client
         database context.
        :param external_data  External data to send with the query
        :return: bytes representing raw ClickHouse return value based on format
        """
        ...

    @abstractmethod
    def raw_stream(
        self,
        query: str,
        parameters: Sequence | dict[str, Any] | None = ...,
        settings: dict[str, Any] | None = ...,
        fmt: str = ...,
        use_database: bool = ...,
        external_data: ExternalData | None = ...,
    ) -> io.IOBase:
        """
        Query method that returns the result as an io.IOBase iterator
        :param query: Query statement/format string
        :param parameters: Optional dictionary used to format the query
        :param settings: Optional dictionary of ClickHouse settings (key/string values)
        :param fmt: ClickHouse output format
        :param use_database  Send the database parameter to ClickHouse so the command will be executed in the client
        database context.
        :param external_data  External data to send with the query
        :return: io.IOBase stream/iterator for the result
        """
        ...

    def query_np(
        self,
        query: str | None = ...,
        parameters: Sequence | dict[str, Any] | None = ...,
        settings: dict[str, Any] | None = ...,
        query_formats: dict[str, str] | None = ...,
        column_formats: dict[str, str] | None = ...,
        encoding: str | None = ...,
        use_none: bool | None = ...,
        max_str_len: int | None = ...,
        context: QueryContext = ...,
        external_data: ExternalData | None = ...,
    ):
        """
        Query method that returns the results as a numpy array.  For parameter values, see the
        create_query_context method
        :return: Numpy array representing the result set
        """

    def query_np_stream(
        self,
        query: str | None = ...,
        parameters: Sequence | dict[str, Any] | None = ...,
        settings: dict[str, Any] | None = ...,
        query_formats: dict[str, str] | None = ...,
        column_formats: dict[str, str] | None = ...,
        encoding: str | None = ...,
        use_none: bool | None = ...,
        max_str_len: int | None = ...,
        context: QueryContext = ...,
        external_data: ExternalData | None = ...,
    ) -> StreamContext:
        """
        Query method that returns the results as a stream of numpy arrays.  For parameter values, see the
        create_query_context method
        :return: Generator that yield a numpy array per block representing the result set
        """

    def query_df(
        self,
        query: str | None = ...,
        parameters: Sequence | dict[str, Any] | None = ...,
        settings: dict[str, Any] | None = ...,
        query_formats: dict[str, str] | None = ...,
        column_formats: dict[str, str] | None = ...,
        encoding: str | None = ...,
        use_none: bool | None = ...,
        max_str_len: int | None = ...,
        use_na_values: bool | None = ...,
        query_tz: str | None = ...,
        column_tzs: dict[str, str | tzinfo] | None = ...,
        context: QueryContext = ...,
        external_data: ExternalData | None = ...,
        use_extended_dtypes: bool | None = ...,
    ):
        """
        Query method that results the results as a pandas dataframe.  For parameter values, see the
        create_query_context method
        :return: Pandas dataframe representing the result set
        """

    def query_df_stream(
        self,
        query: str | None = ...,
        parameters: Sequence | dict[str, Any] | None = ...,
        settings: dict[str, Any] | None = ...,
        query_formats: dict[str, str] | None = ...,
        column_formats: dict[str, str] | None = ...,
        encoding: str | None = ...,
        use_none: bool | None = ...,
        max_str_len: int | None = ...,
        use_na_values: bool | None = ...,
        query_tz: str | None = ...,
        column_tzs: dict[str, str | tzinfo] | None = ...,
        context: QueryContext = ...,
        external_data: ExternalData | None = ...,
        use_extended_dtypes: bool | None = ...,
    ) -> StreamContext:
        """
        Query method that returns the results as a StreamContext.  For parameter values, see the
        create_query_context method
        :return: Generator that yields a Pandas dataframe per block representing the result set
        """

    def create_query_context(
        self,
        query: str | bytes | None = ...,
        parameters: Sequence | dict[str, Any] | None = ...,
        settings: dict[str, Any] | None = ...,
        query_formats: dict[str, str] | None = ...,
        column_formats: dict[str, str | dict[str, str]] | None = ...,
        encoding: str | None = ...,
        use_none: bool | None = ...,
        column_oriented: bool | None = ...,
        use_numpy: bool | None = ...,
        max_str_len: int | None = ...,
        context: QueryContext | None = ...,
        query_tz: str | tzinfo | None = ...,
        column_tzs: dict[str, str | tzinfo] | None = ...,
        use_na_values: bool | None = ...,
        streaming: bool = ...,
        as_pandas: bool = ...,
        external_data: ExternalData | None = ...,
        use_extended_dtypes: bool | None = ...,
    ) -> QueryContext:
        """
        Creates or updates a reusable QueryContext object
        :param query: Query statement/format string
        :param parameters: Optional dictionary used to format the query
        :param settings: Optional dictionary of ClickHouse settings (key/string values)
        :param query_formats: See QueryContext __init__ docstring
        :param column_formats: See QueryContext __init__ docstring
        :param encoding: See QueryContext __init__ docstring
        :param use_none: Use None for ClickHouse NULL instead of default values.  Note that using None in Numpy
          arrays will force the numpy array dtype to 'object', which is often inefficient.  This effect also
          will impact the performance of Pandas dataframes.
        :param column_oriented: Deprecated. Controls orientation of the QueryResult result_set property
        :param use_numpy: Return QueryResult columns as one-dimensional numpy arrays
        :param max_str_len: Limit returned ClickHouse String values to this length, which allows a Numpy
          structured array even with ClickHouse variable length String columns.  If 0, Numpy arrays for
          String columns will always be object arrays
        :param context: An existing QueryContext to be updated with any provided parameter values
        :param query_tz  Either a string or a pytz tzinfo object.  (Strings will be converted to tzinfo objects).
          Values for any DateTime or DateTime64 column in the query will be converted to Python datetime.datetime
          objects with the selected timezone.
        :param column_tzs A dictionary of column names to tzinfo objects (or strings that will be converted to
          tzinfo objects).  The timezone will be applied to datetime objects returned in the query
        :param use_na_values: Deprecated alias for use_advanced_dtypes
        :param as_pandas Return the result columns as pandas.Series objects
        :param streaming Marker used to correctly configure streaming queries
        :param external_data ClickHouse "external data" to send with query
        :param use_extended_dtypes:  Only relevant to Pandas Dataframe queries.  Use Pandas "missing types", such as
          pandas.NA and pandas.NaT for ClickHouse NULL values, as well as extended Pandas dtypes such as IntegerArray
          and StringArray.  Defaulted to True for query_df methods
        :return: Reusable QueryContext
        """

    def query_arrow(
        self,
        query: str,
        parameters: Sequence | dict[str, Any] | None = ...,
        settings: dict[str, Any] | None = ...,
        use_strings: bool | None = ...,
        external_data: ExternalData | None = ...,
    ):
        """
        Query method using the ClickHouse Arrow format to return a PyArrow table
        :param query: Query statement/format string
        :param parameters: Optional dictionary used to format the query
        :param settings: Optional dictionary of ClickHouse settings (key/string values)
        :param use_strings:  Convert ClickHouse String type to Arrow string type (instead of binary)
        :param external_data ClickHouse "external data" to send with query
        :return: PyArrow.Table
        """

    def query_arrow_stream(
        self,
        query: str,
        parameters: Sequence | dict[str, Any] | None = ...,
        settings: dict[str, Any] | None = ...,
        use_strings: bool | None = ...,
        external_data: ExternalData | None = ...,
    ) -> StreamContext:
        """
        Query method that returns the results as a stream of Arrow tables
        :param query: Query statement/format string
        :param parameters: Optional dictionary used to format the query
        :param settings: Optional dictionary of ClickHouse settings (key/string values)
        :param use_strings:  Convert ClickHouse String type to Arrow string type (instead of binary)
        :param external_data ClickHouse "external data" to send with query
        :return: Generator that yields a PyArrow.Table for per block representing the result set
        """

    @abstractmethod
    def command(
        self,
        cmd: str,
        parameters: Sequence[Any] | dict[str, Any] | None = None,
        data: str | bytes | None = None,
        settings: dict[str, Any] | None = None,
        use_database: bool = True,
        external_data: ExternalData | None = None,
    ) -> str | int | Sequence[str] | QuerySummary:
        """
        Client method that returns a single value instead of a result set
        :param cmd: ClickHouse query/command as a python format string
        :param parameters: Optional dictionary of key/values pairs to be formatted
        :param data: Optional 'data' for the command (for INSERT INTO in particular)
        :param settings: Optional dictionary of ClickHouse settings (key/string values)
        :param use_database: Send the database parameter to ClickHouse so the command will be executed in the client
         database context.  Otherwise, no database will be specified with the command.  This is useful for determining
         the default user database
        :param external_data ClickHouse "external data" to send with command/query
        :return: Decoded response from ClickHouse as either a string, int, or sequence of strings, or QuerySummary
        if no data returned
        """
        ...

    @abstractmethod
    def ping(self) -> bool:
        """
        Validate the connection, does not throw an Exception (see debug logs)
        :return: ClickHouse server is up and reachable
        """
        ...

    def insert(
        self,
        table: str | None = ...,
        data: Sequence[Sequence[Any]] = ...,
        column_names: str | Iterable[str] = ...,
        database: str | None = ...,
        column_types: Sequence[ClickHouseType] = ...,
        column_type_names: Sequence[str] = ...,
        column_oriented: bool = ...,
        settings: dict[str, Any] | None = ...,
        context: InsertContext = ...,
    ) -> QuerySummary:
        """
        Method to insert multiple rows/data matrix of native Python objects.  If context is specified arguments
        other than data are ignored
        :param table: Target table
        :param data: Sequence of sequences of Python data
        :param column_names: Ordered list of column names or '*' if column types should be retrieved from the
            ClickHouse table definition
        :param database: Target database -- will use client default database if not specified.
        :param column_types: ClickHouse column types.  If set then column data does not need to be retrieved from
            the server
        :param column_type_names: ClickHouse column type names.  If set then column data does not need to be
            retrieved from the server
        :param column_oriented: If true the data is already "pivoted" in column form
        :param settings: Optional dictionary of ClickHouse settings (key/string values)
        :param context: Optional reusable insert context to allow repeated inserts into the same table with
            different data batches
        :return: QuerySummary with summary information, throws exception if insert fails
        """

    def insert_df(
        self,
        table: str = ...,
        df=...,
        database: str | None = ...,
        settings: dict | None = ...,
        column_names: Sequence[str] | None = ...,
        column_types: Sequence[ClickHouseType] = ...,
        column_type_names: Sequence[str] = ...,
        context: InsertContext = ...,
    ) -> QuerySummary:
        """
        Insert a pandas DataFrame into ClickHouse.  If context is specified arguments other than df are ignored
        :param table: ClickHouse table
        :param df: two-dimensional pandas dataframe
        :param database: Optional ClickHouse database
        :param settings: Optional dictionary of ClickHouse settings (key/string values)
        :param column_names: An optional list of ClickHouse column names.  If not set, the DataFrame column names
           will be used
        :param column_types: ClickHouse column types.  If set then column data does not need to be retrieved from
            the server
        :param column_type_names: ClickHouse column type names.  If set then column data does not need to be
            retrieved from the server
        :param context: Optional reusable insert context to allow repeated inserts into the same table with
            different data batches
        :return: QuerySummary with summary information, throws exception if insert fails
        """

    def insert_arrow(self, table: str, arrow_table, database: str = ..., settings: dict | None = ...) -> QuerySummary:
        """
        Insert a PyArrow table DataFrame into ClickHouse using raw Arrow format
        :param table: ClickHouse table
        :param arrow_table: PyArrow Table object
        :param database: Optional ClickHouse database
        :param settings: Optional dictionary of ClickHouse settings (key/string values)
        :return: QuerySummary with summary information, throws exception if insert fails
        """

    def create_insert_context(
        self,
        table: str,
        column_names: str | Sequence[str] | None = ...,
        database: str | None = ...,
        column_types: Sequence[ClickHouseType] = ...,
        column_type_names: Sequence[str] = ...,
        column_oriented: bool = ...,
        settings: dict[str, Any] | None = ...,
        data: Sequence[Sequence[Any]] | None = ...,
    ) -> InsertContext:
        """
        Builds a reusable insert context to hold state for a duration of an insert
        :param table: Target table
        :param database: Target database.  If not set, uses the client default database
        :param column_names: Optional ordered list of column names.  If not set, all columns ('*') will be assumed
          in the order specified by the table definition
        :param database: Target database -- will use client default database if not specified
        :param column_types: ClickHouse column types.  Optional  Sequence of ClickHouseType objects.  If neither column
           types nor column type names are set, actual column types will be retrieved from the server.
        :param column_type_names: ClickHouse column type names.  Specified column types by name string
        :param column_oriented: If true the data is already "pivoted" in column form
        :param settings: Optional dictionary of ClickHouse settings (key/string values)
        :param data: Initial dataset for insert
        :return Reusable insert context
        """

    def min_version(self, version_str: str) -> bool:
        """
        Determine whether the connected server is at least the submitted version
        For Altinity Stable versions like 22.8.15.25.altinitystable
        the last condition in the first list comprehension expression is added
        :param version_str: A version string consisting of up to 4 integers delimited by dots
        :return: True if version_str is greater than the server_version, False if less than
        """

    @abstractmethod
    def data_insert(self, context: InsertContext) -> QuerySummary:
        """
        Subclass implementation of the data insert
        :context: InsertContext parameter object
        :return: No return, throws an exception if the insert fails
        """
        ...

    @abstractmethod
    def raw_insert(
        self,
        table: str,
        column_names: Sequence[str] | None = ...,
        insert_block: str | bytes | Generator[bytes, None, None] | BinaryIO = ...,
        settings: dict | None = ...,
        fmt: str | None = ...,
        compression: str | None = ...,
    ) -> QuerySummary:
        """
        Insert data already formatted in a bytes object
        :param table: Table name (whether qualified with the database name or not)
        :param column_names: Sequence of column names
        :param insert_block: Binary or string data already in a recognized ClickHouse format
        :param settings:  Optional dictionary of ClickHouse settings (key/string values)
        :param compression:  Recognized ClickHouse `Accept-Encoding` header compression value
        :param fmt: Valid clickhouse format
        """
        ...

    def close(self):  # -> None:
        """
        Subclass implementation to close the connection to the server/deallocate the client
        """

    def __enter__(self):  # -> Self:
        ...
    def __exit__(self, exc_type, exc_value, exc_traceback):  # -> None:
        ...
