"""
This type stub file was generated by pyright.
"""

from typing import Any

logger = ...
_empty_map = ...

class BaseQueryContext:
    def __init__(
        self,
        settings: dict[str, Any] | None = ...,
        query_formats: dict[str, str] | None = ...,
        column_formats: dict[str, str | dict[str, str]] | None = ...,
        encoding: str | None = ...,
        use_extended_dtypes: bool = ...,
        use_numpy: bool = ...,
    ) -> None: ...
    def start_column(self, name: str):  # -> None:
        ...
    def active_fmt(self, ch_type):  # -> str | None:
        ...
