"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence

logger = ...

class ExternalFile:
    def __init__(
        self,
        file_path: str | None = ...,
        file_name: str | None = ...,
        data: bytes | None = ...,
        fmt: str | None = ...,
        types: str | Sequence[str] | None = ...,
        structure: str | Sequence[str] | None = ...,
        mime_type: str | None = ...,
    ) -> None: ...
    @property
    def form_data(self) -> tuple: ...
    @property
    def query_params(self) -> dict[str, str]: ...

class ExternalData:
    def __init__(
        self,
        file_path: str | None = ...,
        file_name: str | None = ...,
        data: bytes | None = ...,
        fmt: str | None = ...,
        types: str | Sequence[str] | None = ...,
        structure: str | Sequence[str] | None = ...,
        mime_type: str | None = ...,
    ) -> None: ...
    def add_file(
        self,
        file_path: str | None = ...,
        file_name: str | None = ...,
        data: bytes | None = ...,
        fmt: str | None = ...,
        types: str | Sequence[str] | None = ...,
        structure: str | Sequence[str] | None = ...,
        mime_type: str | None = ...,
    ):  # -> None:
        ...
    @property
    def form_data(self) -> dict[str, tuple]: ...
    @property
    def query_params(self) -> dict[str, str]: ...
