"""
This type stub file was generated by pyright.
"""

from collections.abc import Generator, Sequence

from clickhouse_connect.driver.common import StreamContext
from clickhouse_connect.driver.types import Closable

logger = ...

class NumpyResult(Closable):
    def __init__(
        self,
        block_gen: Generator[Sequence, None, None] = ...,
        column_names: tuple = ...,
        column_types: tuple = ...,
        d_types: Sequence = ...,
        source: Closable = ...,
    ) -> None: ...
    def close_numpy(self):  # -> Self:
        ...
    def close_df(self):  # -> Self:
        ...
    @property
    def np_result(self):  # -> None:
        ...
    @property
    def df_result(self):  # -> None:
        ...
    @property
    def np_stream(self) -> StreamContext: ...
    @property
    def df_stream(self) -> StreamContext: ...
    def close(self):  # -> None:
        ...
