"""
This type stub file was generated by pyright.
"""

import pytz
import tzlocal

tzlocal = ...
local_tz: pytz.timezone
local_tz_dst_safe: bool = ...

def normalize_timezone(timezone: pytz.timezone) -> tuple[pytz.timezone, bool]: ...

local_tz = ...
