services:
  postgres:
    image: postgres:latest
    container_name: postgres_research
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - research_postgres:/var/lib/postgresql/data/pgdata

volumes: 
  research_postgres:
