"""
This type stub file was generated by pyright.
"""

from enum import StrEnum
from typing import Any

from pydantic import BaseModel

class Granularity(StrEnum):
    """
    Time Series Granuality
    """

    seconds = ...
    minutes = ...
    hours = ...

class TimeSeriesConfig(BaseModel):
    """
    Time Series Collection config
    """

    time_field: str
    meta_field: str | None = ...
    granularity: Granularity | None = ...
    bucket_max_span_seconds: int | None = ...
    bucket_rounding_second: int | None = ...
    expire_after_seconds: int | None = ...
    def build_query(self, collection_name: str) -> dict[str, Any]: ...
