"""
This type stub file was generated by pyright.
"""

import abc

class AbstractType:
    __metaclass__ = abc.ABCMeta
    @abc.abstractmethod
    def encode(cls, value):  # -> None:
        ...
    @abc.abstractmethod
    def decode(cls, data):  # -> None:
        ...
    @classmethod
    def repr(cls, value):  # -> str:
        ...
